name: Combine Provider Files and Publish Release

on:
  push:
    paths:
      - 'rule-providers/direct/**'
      - 'rule-providers/proxy/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: 安装依赖并生成 direct.yaml 和 proxy.yaml
      - name: Combine YAML files
        run: |
          pip install pyyaml
          python combine_yaml.py rule-providers/direct rule-providers/direct.yaml
          python combine_yaml.py rule-providers/proxy rule-providers/proxy.yaml

      # Step 4: 创建 Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: auto-update-$(date +'%Y%m%d%H%M%S')
          release_name: Auto Update Provider Files
          draft: false
          prerelease: false

      # Step 5: 上传 direct.yaml
      - name: Upload direct.yaml to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rule-providers/direct.yaml
          asset_name: direct.yaml
          asset_content_type: text/yaml

      # Step 6: 上传 proxy.yaml
      - name: Upload proxy.yaml to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rule-providers/proxy.yaml
          asset_name: proxy.yaml
          asset_content_type: text/yaml
