name: Combine Provider Files and Publish Release

on:
  push:
    paths:
      - "rule-providers/direct/**"
      - "rule-providers/proxy/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: 安装依赖并生成 direct.yaml 和 proxy.yaml
      - name: Install dependencies and generate YAML files
        run: |
          pip install pyyaml
          python combine_yaml.py rule-providers/direct rule-providers/direct.yaml
          python combine_yaml.py rule-providers/proxy rule-providers/proxy.yaml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rule-providers/direct.yaml
            rule-providers/proxy.yaml
